# Generated by Django 4.2.5 on 2023-10-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coincollection',
            name='comment',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='coincollection',
            name='denomination',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coincollection',
            name='mint_mark',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='coincollection',
            name='mintage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coincollection',
            name='pcgs_cert_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coincollection',
            name='point_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coincollection',
            name='variety',
            field=models.CharField(null=True),
        ),
    ]
