# Generated by Django 4.2.5 on 2023-10-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_collection', '0002_coincollection_comment_coincollection_denomination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coincollection',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
