# Generated by Django 4.2.5 on 2023-10-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='comment',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='mint_mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='pcgs_cert_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='mintage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='point_value',
            field=models.IntegerField(null=True),
        ),
    ]
