# Generated by Django 4.2.5 on 2023-10-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_coin_comment_coin_mint_mark_coin_pcgs_cert_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='mint_mark',
            field=models.CharField(null=True),
        ),
    ]
