# Generated by Django 4.2.5 on 2023-10-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_alter_coin_mint_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
