# Generated by Django 4.2.5 on 2023-10-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_coin_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='quantity',
        ),
    ]
