# Generated by Django 4.2.5 on 2023-10-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0005_remove_coin_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
                ('point_value', models.CharField()),
                ('category', models.BooleanField()),
            ],
        ),
    ]
