# Generated by Django 4.2.5 on 2023-10-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_coin_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
    ]
