# Generated by Django 4.2.5 on 2023-10-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dollar_value_searched',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
